---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	prepare_context(prepare_context)
	summarize_from_vector(summarize_from_vector)
	summarize_from_web(summarize_from_web)
	weather_fanout(weather_fanout)
	fetch_weather(fetch_weather)
	fetch_weather_only(fetch_weather_only)
	fetch_images(fetch_images)
	finalize_response(finalize_response)
	finalize_weather_only(finalize_weather_only)
	__end__([<p>__end__</p>]):::last
	__start__ --> prepare_context;
	fetch_images --> finalize_response;
	fetch_weather --> finalize_response;
	fetch_weather_only --> finalize_weather_only;
	prepare_context -. &nbsp;weather_only&nbsp; .-> fetch_weather_only;
	prepare_context -. &nbsp;vector&nbsp; .-> summarize_from_vector;
	prepare_context -. &nbsp;web&nbsp; .-> summarize_from_web;
	summarize_from_vector --> weather_fanout;
	summarize_from_web --> weather_fanout;
	weather_fanout --> fetch_images;
	weather_fanout --> fetch_weather;
	finalize_response --> __end__;
	finalize_weather_only --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
